using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Config
{
    /// <summary>
    /// Last line of defence against config injection. Models are validated before they reach
    /// the database, but the renderers never trust that: a newline or '[' in a value could
    /// start a new section in the generated file.
    /// </summary>
    internal static class ConfText
    {
        public const string Header = "; Generated by TNPBX. Do not edit: changes will be overwritten.";

        private static readonly char[] Forbidden = { '\r', '\n', '\0', ';', '[', ']', '"' };

        /// <summary>What would split one field of a comma separated line into two.</summary>
        private static readonly char[] FieldSeparators = { ',', '|', '=' };

        /// <summary>
        /// A caller ID written the way Asterisk's own <c>CALLERID(all)</c> reads it: <c>"Name"
        /// &lt;number&gt;</c>, or the bare number when no name was typed (D125).
        ///
        /// The quotes are ours. <see cref="Safe"/> refuses a value with a quote in it, so the two
        /// parts are checked separately and then wrapped, which is the same thing the endpoint
        /// <c>callerid</c> lines do. A value that is not a caller ID at all is refused rather than
        /// written: the models validate it first, and this is the last line of defence.
        /// </summary>
        public static string CallerID(string value, string field)
        {
            if (!CallerIDFormat.TryParse(value, out var name, out var number))
                throw new InvalidOperationException($"Refusing to write unsafe value for '{field}' to Asterisk config.");

            var digits = Safe(number, field);

            return name.Length == 0 ? digits : $"\"{Safe(name, field)}\" <{digits}>";
        }

        /// <summary>
        /// Enabled extensions in numeric order, re-validated so a bad row can't reach a config file.
        /// </summary>
        public static List<Extension> EnabledInOrder(IEnumerable<Extension> extensions)
        {
            var enabled = extensions.Where(e => e.Enabled).ToList();

            foreach (var extension in enabled)
            {
                var errors = extension.Validate();
                if (errors.Count > 0)
                    throw new InvalidOperationException($"Extension '{extension.Number}' is invalid: {string.Join(" ", errors)}");
            }

            return enabled
                .OrderBy(e => e.Number.Length)
                .ThenBy(e => e.Number, StringComparer.Ordinal)
                .ToList();
        }

        public static string Safe(string value, string field)
        {
            if (value.IndexOfAny(Forbidden) >= 0 || value.Any(char.IsControl))
                throw new InvalidOperationException($"Refusing to write unsafe value for '{field}' to Asterisk config.");
            return value;
        }

        /// <summary>
        /// A value for one field of a comma separated line, which is how voicemail.conf writes a
        /// mailbox. A comma, pipe or equals sign would end the field early and shift everything
        /// after it, so they become spaces rather than throwing: "Smith, John" is a name our own
        /// rules allow, and an apply must not fail over it. Everything else still goes through
        /// <see cref="Safe"/>.
        /// </summary>
        public static string SafeField(string value, string field)
        {
            var separators = value.IndexOfAny(FieldSeparators) < 0
                ? value
                : new string(value.Select(c => Array.IndexOf(FieldSeparators, c) >= 0 ? ' ' : c).ToArray());

            return Safe(separators, field);
        }
    }
}
