using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Config
{
    /// <summary>
    /// Last line of defence against config injection. Models are validated before they reach
    /// the database, but the renderers never trust that: a newline or '[' in a value could
    /// start a new section in the generated file.
    /// </summary>
    internal static class ConfText
    {
        public const string Header = "; Generated by TNPBX. Do not edit: changes will be overwritten.";

        private static readonly char[] Forbidden = { '\r', '\n', '\0', ';', '[', ']', '"' };

        /// <summary>
        /// Enabled extensions in numeric order, re-validated so a bad row can't reach a config file.
        /// </summary>
        public static List<Extension> EnabledInOrder(IEnumerable<Extension> extensions)
        {
            var enabled = extensions.Where(e => e.Enabled).ToList();

            foreach (var extension in enabled)
            {
                var errors = extension.Validate();
                if (errors.Count > 0)
                    throw new InvalidOperationException($"Extension '{extension.Number}' is invalid: {string.Join(" ", errors)}");
            }

            return enabled
                .OrderBy(e => e.Number.Length)
                .ThenBy(e => e.Number, StringComparer.Ordinal)
                .ToList();
        }

        public static string Safe(string value, string field)
        {
            if (value.IndexOfAny(Forbidden) >= 0 || value.Any(char.IsControl))
                throw new InvalidOperationException($"Refusing to write unsafe value for '{field}' to Asterisk config.");
            return value;
        }
    }
}
