using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Config
{
    /// <summary>
    /// Renders <c>tnpbx-voicemail-options.json</c>: what the <c>voicemail-mail</c> script should do
    /// with a message beyond relaying it, per mailbox. Today that is one thing — transcribe it or
    /// not (D128). Pure function: no I/O.
    ///
    /// <para><b>Why a file of our own rather than voicemail.conf.</b> app_voicemail has no
    /// transcription option and no way to pass one to <c>mailcmd</c>: the command is a fixed string
    /// with no arguments, and the script gets the composed email on stdin and nothing else. An
    /// invented per-mailbox option in voicemail.conf would reach app_voicemail's own option parser,
    /// which answers an unknown one with a warning per mailbox on every reload and is under no
    /// obligation to keep ignoring it — and the script would then have to parse voicemail.conf to
    /// read it back. A small generated file that says exactly what it means is cheaper than
    /// both.</para>
    ///
    /// <para><b>Why /etc/asterisk.</b> This is generated from the extension rows like every other
    /// file there, so it belongs to an apply (D4) and is written by the same atomic writer; and the
    /// asterisk user — which is what Asterisk runs the script as — already reads that directory
    /// through the group (D18). It is not mail.json's neighbour in /opt/tnpbx/Config because
    /// nothing here is a credential and nothing here is a setting: it is rendered output.</para>
    ///
    /// <para>Asterisk itself never reads this file. It carries no PIN, no address and no secret —
    /// a mailbox number and a boolean — so a group-readable conf directory is a fine place for
    /// it.</para>
    /// </summary>
    public static class VoicemailOptionsRenderer
    {
        /// <summary>
        /// Where it is written, and the path the script has compiled into it. The <c>tnpbx-</c>
        /// prefix says at a glance that it is ours rather than something Asterisk reads.
        /// </summary>
        public const string FileName = "tnpbx-voicemail-options.json";

        /// <summary>
        /// The "do not edit" line, in the only form a JSON file can carry one. Named so the test
        /// and the script agree that it is a comment and not data.
        /// </summary>
        private const string GeneratedNote =
            "Generated by TNPBX from the extension list. Do not edit: changes will be overwritten.";

        /// <summary>
        /// One entry per mailbox that voicemail.conf will contain, in the same order, so the two
        /// files can be read side by side and a missing entry means "no such mailbox" rather than
        /// "options not written yet". A mailbox with no address gets <c>Transcribe: false</c>
        /// whatever the extension asked for: there is no email to put a transcript in.
        ///
        /// <para>A <see cref="JsonObject"/> rather than a dictionary because it keeps the order
        /// things were put into it, and a file whose lines move about would be rewritten — and
        /// app_voicemail reloaded — by an apply that changed nothing.</para>
        /// </summary>
        public static string Render(IEnumerable<Extension> extensions)
        {
            var mailboxes = new JsonObject();

            foreach (var extension in ConfText.EnabledInOrder(extensions).Where(e => e.VoicemailEnabled))
            {
                // Safe rather than SafeField: this is a JSON key, not a comma separated field, and
                // an extension number is digits — a value that is not is a row that never went
                // through the repository, and it stops the apply the way it does everywhere else.
                var number = ConfText.Safe(extension.Number, "number");
                var email = ConfText.SafeField(extension.VoicemailEmail, "voicemail email");

                mailboxes[number] = new JsonObject
                {
                    ["Transcribe"] = email.Length > 0 && extension.VoicemailTranscribe,
                };
            }

            var root = new JsonObject
            {
                ["Generated"] = GeneratedNote,
                ["Mailboxes"] = mailboxes,
            };

            var json = root.ToJsonString(new JsonSerializerOptions
            {
                // The strictest encoder: nothing in here should ever need escaping, and a
                // generated file that is read by a script is not a place for surprises.
                Encoder = JavaScriptEncoder.Default,
                WriteIndented = true,
            });

            // A trailing newline, like every other file this application generates.
            return json.ReplaceLineEndings("\n") + "\n";
        }
    }
}
