using Techie.Pbx.Asterisk.Config;

namespace Techie.Pbx.Tests.Asterisk
{
    /// <summary>
    /// notify.conf is fully static content (D91), so a light inline-assertion test is enough —
    /// no golden file, unlike the renderers whose output depends on the database.
    /// </summary>
    public class NotifyConfRendererTests
    {
        [Fact]
        public void Both_notification_categories_are_present()
        {
            var actual = NotifyConfRenderer.Render();

            Assert.Contains("[tnpbx-check-cfg]\n", actual);
            Assert.Contains("[tnpbx-reboot]\n", actual);
        }

        /// <summary>
        /// A bare check-sync re-fetches config; adding reboot=true also reboots the phone. Both
        /// are well-established Yealink NOTIFY semantics.
        /// </summary>
        [Fact]
        public void Check_config_and_reboot_send_different_events()
        {
            var actual = NotifyConfRenderer.Render();

            Assert.Contains("Event = check-sync\n", actual);
            Assert.Contains("Event = check-sync;reboot=true\n", actual);
        }

        [Fact]
        public void It_is_a_normal_generated_conf_file()
        {
            Assert.StartsWith(ConfTextHeader, NotifyConfRenderer.Render());
        }

        // ConfText.Header is internal; the exact leading comment text is duplicated here rather
        // than exposing it further, since it never changes independently of the other renderers.
        private const string ConfTextHeader = "; Generated by TNPBX. Do not edit: changes will be overwritten.";
    }
}
