using System.Globalization;
using System.Text;

namespace Techie.Pbx.Asterisk.Provisioning
{
    /// <summary>
    /// One phone's configuration, generated from its row and the extension it is linked to. Pure
    /// function: data in, text out, no lookups and no I/O — the file is never written to disk, it
    /// is generated for each request and handed straight to the phone (D79).
    ///
    /// A phone with no extension still gets a valid file: the time and a provisioning poll, and no
    /// registration. That is what lets a phone auto-register itself, sit on a desk showing the
    /// right time, and start working the moment an admin assigns it an extension and it polls
    /// again (D78).
    /// </summary>
    public static class PolycomConfigRenderer
    {
        /// <summary>
        /// What a caller may dial without pressing send. Four-digit extensions, a feature code
        /// (<c>*97</c>, <c>*43</c>) ended by a pause, the N11 services, and an operator "0" with a
        /// pause after it.
        ///
        /// Extensions here may be 2 to 6 digits (<c>Extension.IsValidNumber</c>), so a site whose
        /// extensions are not 4 digits gets a phone that waits for the inter-digit timeout instead
        /// of dialling at once. That is the agreed shape for this piece; making the map follow the
        /// real extension lengths is a question to ask, not a thing to guess.
        /// </summary>
        private const string DigitMap = "xxxx|*xx.T|[2-9]11|0T";

        /// <summary>Seconds the phone waits for another digit before dialling what it has.</summary>
        private const int DigitMapTimeoutSeconds = 3;

        /// <summary>How long the phone's registration lasts before it renews, in seconds.</summary>
        private const int RegistrationExpiration = 3600;

        /// <summary>
        /// How often the phone comes back for its config, in seconds. A day: long enough not to be
        /// a load on the server, short enough that assigning an extension takes effect without
        /// anyone walking to the desk. Rebooting the phone is the impatient version.
        /// </summary>
        private const int ProvisioningPollSeconds = 86400;

        /// <summary>The transport the phone registers over, matching the UDP transport we render.</summary>
        private const string Transport = "UDPOnly";

        public static string Render(PolycomConfig config)
        {
            var phone = config.Phone;

            var phoneErrors = phone.Validate();
            if (phoneErrors.Count > 0)
                throw new InvalidOperationException($"Phone '{phone.Mac}' is invalid: {string.Join(" ", phoneErrors)}");

            var sb = new StringBuilder();
            var mac = PolycomXml.Value(phone.Mac, "mac");

            sb.Append(PolycomXml.Declaration).Append('\n');
            PolycomXml.Comment(sb, "", $"Generated by TNPBX for {mac} per request. Nothing is stored on disk; edit the phone in TNPBX.");
            sb.Append("<polycomConfig>\n");

            // The time, and coming back for this file again: the two things every phone gets,
            // whether or not anyone has told it which extension it is.
            PolycomXml.Element(sb, "  ", "tcpIpApp", new[]
            {
                PolycomXml.Attribute("tcpIpApp.sntp.address", config.SntpAddress, "sntp address"),
                PolycomXml.Constant("tcpIpApp.sntp.gmtOffset", Number(config.GmtOffsetSeconds)),
            });

            PolycomXml.Element(sb, "  ", "prov", new[]
            {
                PolycomXml.Constant("prov.polling.enabled", "1"),
                PolycomXml.Constant("prov.polling.mode", "rel"),
                PolycomXml.Constant("prov.polling.period", Number(ProvisioningPollSeconds)),
            });

            // Phone-level, not extension-level, so it goes out whether or not anyone has been
            // assigned yet. Unset means left out rather than written blank: a blank password is
            // worse than no opinion at all (D84).
            var deviceAuth = new List<(string Name, string Value)>();
            if (config.AdminPassword.Length > 0)
                deviceAuth.Add(PolycomXml.Attribute("device.auth.localAdminPassword", config.AdminPassword, "device admin password"));
            if (config.UserPassword.Length > 0)
                deviceAuth.Add(PolycomXml.Attribute("device.auth.localUserPassword", config.UserPassword, "device user password"));

            if (deviceAuth.Count > 0)
                PolycomXml.Element(sb, "  ", "device", deviceAuth);

            if (config.Extension == null)
            {
                PolycomXml.Comment(sb, "  ", "No extension is assigned to this phone yet, so it is given no registration.");
                sb.Append("</polycomConfig>\n");

                return sb.ToString();
            }

            var extension = config.Extension;

            var extensionErrors = extension.Validate();
            if (extensionErrors.Count > 0)
                throw new InvalidOperationException($"Extension '{extension.Number}' is invalid: {string.Join(" ", extensionErrors)}");

            PolycomXml.Element(sb, "  ", "dialplan", new[]
            {
                PolycomXml.Constant("dialplan.digitmap", DigitMap),
                PolycomXml.Constant("dialplan.digitmap.timeOut", Number(DigitMapTimeoutSeconds)),
            });

            // A port of its own per phone, so two phones behind one NAT cannot collide (D81).
            PolycomXml.Element(sb, "  ", "voIpProt", new[]
            {
                PolycomXml.Constant("voIpProt.SIP.local.port", Number(phone.LocalSipPort)),
            });

            PolycomXml.Element(sb, "  ", "reg", new[]
            {
                PolycomXml.Attribute("reg.1.displayName", extension.Name, "display name"),
                PolycomXml.Attribute("reg.1.address", extension.Number, "address"),
                PolycomXml.Attribute("reg.1.auth.userId", extension.Number, "auth user"),
                PolycomXml.Attribute("reg.1.auth.password", extension.Secret, "auth password"),
                PolycomXml.Attribute("reg.1.server.1.address", config.ServerAddress, "server address"),
                PolycomXml.Constant("reg.1.server.1.port", Number(config.SipPort)),
                PolycomXml.Constant("reg.1.server.1.transport", Transport),
                PolycomXml.Constant("reg.1.server.1.expires", Number(RegistrationExpiration)),
                PolycomXml.Constant("reg.1.lineKeys", "1"),
            });

            // The message waiting light, and a missed call list on the phone itself.
            PolycomXml.Element(sb, "  ", "msg", new[]
            {
                PolycomXml.Attribute("msg.mwi.1.subscribe", extension.Number, "mwi subscribe"),
            });

            PolycomXml.Element(sb, "  ", "call", new[]
            {
                PolycomXml.Constant("call.missedCallTracking.1.enabled", "1"),
            });

            sb.Append("</polycomConfig>\n");

            return sb.ToString();
        }

        private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);
    }
}
