using System.Text;
using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Provisioning
{
    /// <summary>
    /// The master file a Polycom phone asks for first, named after its own MAC address. It is a
    /// pointer and nothing else: it says which application image to run and which file the real
    /// configuration is in, and the phone then fetches that (D77).
    ///
    /// It holds no credentials, which is why an unknown MAC is answered with one. The phone is
    /// added to the database when it comes back for the config file the master names.
    /// </summary>
    public static class PolycomMasterRenderer
    {
        /// <summary>Where the phone keeps the directories it uploads to, relative to our endpoint.</summary>
        private const string ContactsDirectory = "contacts";

        private const string LogDirectory = "logs";

        private const string OverridesDirectory = "overrides";

        /// <summary>
        /// The application image the phone loads. "sip.ld" is the name Polycom's own combined image
        /// uses, and the phone resolves it against the provisioning server — we do not serve it, so
        /// a phone that has no firmware yet keeps the one it is running (D83).
        /// </summary>
        private const string ApplicationImage = "sip.ld";

        public static string Render(string mac)
        {
            if (!Phone.IsValidMac(mac))
                throw new InvalidOperationException($"Refusing to generate a master config for '{mac}', which is not a MAC address.");

            var sb = new StringBuilder();

            sb.Append(PolycomXml.Declaration).Append('\n');
            PolycomXml.Comment(sb, "", "Generated by TNPBX per request. Nothing is stored on disk; edit the phone in TNPBX.");

            PolycomXml.Element(sb, "", "APPLICATION", new[]
            {
                PolycomXml.Constant("APP_FILE_PATH", ApplicationImage),
                PolycomXml.Attribute("CONFIG_FILES", PolycomFiles.ConfigFileName(mac), "config files"),
                PolycomXml.Constant("LOG_FILE_DIRECTORY", LogDirectory),
                PolycomXml.Constant("OVERRIDES_DIRECTORY", OverridesDirectory),
                PolycomXml.Constant("CONTACTS_DIRECTORY", ContactsDirectory),
            });

            return sb.ToString();
        }
    }
}
