using System.Globalization;
using System.Text;
using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Provisioning
{
    /// <summary>
    /// One phone's configuration, generated from its row and the keys assigned to it. Pure
    /// function: data in, text out, no lookups and no I/O — the file is never written to disk, it
    /// is generated for each request and handed straight to the phone (D79).
    ///
    /// The keys are the whole of it (schema 020): the line keys become the <c>reg.N</c>
    /// registrations, in key order, and every other key becomes an attendant resource. So the keys
    /// the Buttons tab shows are the keys the handset has, in the same order, with no ninth line
    /// appearing from somewhere else.
    ///
    /// A phone with no line key still gets a valid file: the time and a provisioning poll, and no
    /// registration. That is what lets a phone auto-register itself, sit on a desk showing the
    /// right time, and start working the moment an admin assigns it an extension and it polls
    /// again (D78).
    /// </summary>
    public static class PolycomConfigRenderer
    {
        /// <summary>
        /// What kind of attendant resource an assigned key is. "automata" is the monitored line:
        /// the phone SUBSCRIBEs to the address (so the lamp follows its hint) and pressing the
        /// key dials it, with the long-press behaviours (pickup, transfer to it) that Polycom
        /// attaches to a monitored key. "normal" would be a plain speed dial with no lamp, which
        /// is not what a key is for here. Both kinds of key we render want exactly this — a
        /// parking slot is dialled to retrieve the call in it, the same gesture as dialling a
        /// colleague (D121).
        /// </summary>
        private const string AttendantType = "automata";

        /// <summary>
        /// What a caller may dial without pressing send. Four-digit extensions, a feature code
        /// (<c>*97</c>, <c>*43</c>) ended by a pause, the N11 services, and an operator "0" with a
        /// pause after it.
        ///
        /// Extensions here may be 2 to 6 digits (<c>Extension.IsValidNumber</c>), so a site whose
        /// extensions are not 4 digits gets a phone that waits for the inter-digit timeout instead
        /// of dialling at once. That is the agreed shape for this piece; making the map follow the
        /// real extension lengths is a question to ask, not a thing to guess.
        /// </summary>
        private const string DigitMap = "xxxx|*xx.T|[2-9]11|0T";

        /// <summary>Seconds the phone waits for another digit before dialling what it has.</summary>
        private const int DigitMapTimeoutSeconds = 3;

        /// <summary>How long the phone's registration lasts before it renews, in seconds.</summary>
        private const int RegistrationExpiration = 3600;

        /// <summary>
        /// How often the phone comes back for its config, in seconds. A day: long enough not to be
        /// a load on the server, short enough that assigning an extension takes effect without
        /// anyone walking to the desk. Rebooting the phone is the impatient version.
        /// </summary>
        private const int ProvisioningPollSeconds = 86400;

        /// <summary>The transport the phone registers over, matching the UDP transport we render.</summary>
        private const string Transport = "UDPOnly";

        public static string Render(PolycomConfig config)
        {
            var phone = config.Phone;

            var phoneErrors = phone.Validate();
            if (phoneErrors.Count > 0)
                throw new InvalidOperationException($"Phone '{phone.Mac}' is invalid: {string.Join(" ", phoneErrors)}");

            var sb = new StringBuilder();
            var mac = PolycomXml.Value(phone.Mac, "mac");

            sb.Append(PolycomXml.Declaration).Append('\n');
            PolycomXml.Comment(sb, "", $"Generated by TNPBX for {mac} per request. Nothing is stored on disk; edit the phone in TNPBX.");
            sb.Append("<polycomConfig>\n");

            // The time, and coming back for this file again: the two things every phone gets,
            // whether or not anyone has told it which extension it is.
            PolycomXml.Element(sb, "  ", "tcpIpApp", new[]
            {
                PolycomXml.Attribute("tcpIpApp.sntp.address", config.SntpAddress, "sntp address"),
                PolycomXml.Constant("tcpIpApp.sntp.gmtOffset", Number(config.GmtOffsetSeconds)),
            });

            PolycomXml.Element(sb, "  ", "prov", new[]
            {
                PolycomXml.Constant("prov.polling.enabled", "1"),
                PolycomXml.Constant("prov.polling.mode", "rel"),
                PolycomXml.Constant("prov.polling.period", Number(ProvisioningPollSeconds)),
            });

            // Phone-level, not extension-level, so it goes out whether or not anyone has been
            // assigned yet. Unset means left out rather than written blank: a blank password is
            // worse than no opinion at all (D84).
            var deviceAuth = new List<(string Name, string Value)>();
            if (config.AdminPassword.Length > 0)
                deviceAuth.Add(PolycomXml.Attribute("device.auth.localAdminPassword", config.AdminPassword, "device admin password"));
            if (config.UserPassword.Length > 0)
                deviceAuth.Add(PolycomXml.Attribute("device.auth.localUserPassword", config.UserPassword, "device user password"));

            if (deviceAuth.Count > 0)
                PolycomXml.Element(sb, "  ", "device", deviceAuth);

            var buttons = Validated(config.Buttons);
            var lines = PhoneButton.Lines(buttons);

            if (lines.Count == 0)
            {
                PolycomXml.Comment(sb, "  ", "No extension is assigned to this phone yet, so it is given no registration.");
                sb.Append("</polycomConfig>\n");

                return sb.ToString();
            }

            PolycomXml.Element(sb, "  ", "dialplan", new[]
            {
                PolycomXml.Constant("dialplan.digitmap", DigitMap),
                PolycomXml.Constant("dialplan.digitmap.timeOut", Number(DigitMapTimeoutSeconds)),
            });

            // A port of its own per phone, so two phones behind one NAT cannot collide (D81).
            PolycomXml.Element(sb, "  ", "voIpProt", new[]
            {
                PolycomXml.Constant("voIpProt.SIP.local.port", Number(phone.LocalSipPort)),
            });

            // One registration per line key, in key order, each taking one line key on the handset.
            var registrations = new List<(string Name, string Value)>();

            for (var index = 0; index < lines.Count; index++)
            {
                var extension = LineExtension(config, lines[index]);
                var reg = $"reg.{Number(index + 1)}";

                registrations.Add(PolycomXml.Attribute($"{reg}.displayName", extension.Name, "display name"));
                registrations.Add(PolycomXml.Attribute($"{reg}.address", extension.Number, "address"));
                registrations.Add(PolycomXml.Attribute($"{reg}.auth.userId", extension.Number, "auth user"));
                registrations.Add(PolycomXml.Attribute($"{reg}.auth.password", extension.Secret, "auth password"));
                registrations.Add(PolycomXml.Attribute($"{reg}.server.1.address", config.ServerAddress, "server address"));
                registrations.Add(PolycomXml.Constant($"{reg}.server.1.port", Number(config.SipPort)));
                registrations.Add(PolycomXml.Constant($"{reg}.server.1.transport", Transport));
                registrations.Add(PolycomXml.Constant($"{reg}.server.1.expires", Number(RegistrationExpiration)));
                registrations.Add(PolycomXml.Constant($"{reg}.lineKeys", "1"));
            }

            PolycomXml.Element(sb, "  ", "reg", registrations);

            // The message waiting light, and a missed call list on the phone itself. The first
            // registration only: a second line is a second person's extension, and their messages
            // are not this phone's to light a lamp about.
            PolycomXml.Element(sb, "  ", "msg", new[]
            {
                PolycomXml.Attribute("msg.mwi.1.subscribe", lines[0].TargetValue, "mwi subscribe"),
            });

            PolycomXml.Element(sb, "  ", "call", new[]
            {
                PolycomXml.Constant("call.missedCallTracking.1.enabled", "1"),
            });

            AppendAttendant(sb, config, buttons.Where(b => !b.IsLine).ToList());

            sb.Append("</polycomConfig>\n");

            return sb.ToString();
        }

        /// <summary>
        /// The keys that are not registrations, written as Polycom's attendant resource list
        /// (D121). Each resource is a lamp and a quick dial: the phone SUBSCRIBEs for the address
        /// in its own dialplan context and dials the same address when the key is pressed. An
        /// extension's lamp follows the <c>PJSIP/&lt;number&gt;</c> hint and a parking slot's
        /// follows <c>park:&lt;slot&gt;@parkedcalls</c>, but that is the dialplan's doing — from
        /// here both are a number in the internal context, which is why this writes both the same
        /// way.
        ///
        /// There is no <c>attendant.uri</c>: that names a server-side resource list, and the list
        /// here is the one this file carries. Nothing is written at all for a phone whose only keys
        /// are its lines, so the rest of its line keys stay whatever the handset does with them.
        ///
        /// The resources are numbered 1..n in key order rather than by the key's own position,
        /// because a phone reads the list until the first index it does not find: a gap left by an
        /// unassigned key would hide every key after it. The consequence, and it is the one to
        /// know: the resources land on the line keys left over after the registrations, in order,
        /// so clearing one moves the rest up a key.
        /// </summary>
        private static void AppendAttendant(StringBuilder sb, PolycomConfig config, List<PhoneButton> buttons)
        {
            if (buttons.Count == 0)
                return;

            // Which registration the subscriptions and the calls go out on: the first line, which
            // is the extension this phone's own user answers as.
            var attributes = new List<(string Name, string Value)>
            {
                PolycomXml.Constant("attendant.reg", "1"),
            };

            for (var index = 0; index < buttons.Count; index++)
            {
                var button = buttons[index];
                var resource = $"attendant.resourceList.{Number(index + 1)}";

                attributes.Add(PolycomXml.Attribute($"{resource}.address", button.TargetValue, "attendant address"));
                attributes.Add(PolycomXml.Attribute($"{resource}.label", button.Label(config.Extensions), "attendant label"));
                attributes.Add(PolycomXml.Constant($"{resource}.type", AttendantType));
            }

            PolycomXml.Comment(sb, "  ", "Keys assigned in TNPBX: a lamp and a quick dial each. An extension's lamp");
            PolycomXml.Comment(sb, "  ", "follows its hint; a parking slot's is lit while a call is sitting in it.");
            PolycomXml.Element(sb, "  ", "attendant", attributes);
        }

        /// <summary>
        /// The extension a line key registers as. The caller has already reduced the keys to the
        /// ones that can work (<see cref="PhoneButton.Usable"/>), so a line naming an extension
        /// this renderer was not given is the caller's mistake and is refused rather than written
        /// as a registration with no password behind it.
        /// </summary>
        private static Extension LineExtension(PolycomConfig config, PhoneButton line)
        {
            var extension = config.Extensions.FirstOrDefault(e =>
                string.Equals(e.Number, line.TargetValue, StringComparison.Ordinal));

            if (extension == null)
                throw new InvalidOperationException($"Phone key {line.Position} registers as extension '{line.TargetValue}', which the renderer was not given.");

            var errors = extension.Validate();
            if (errors.Count > 0)
                throw new InvalidOperationException($"Extension '{extension.Number}' is invalid: {string.Join(" ", errors)}");

            return extension;
        }

        private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

        /// <summary>
        /// The keys in key order, re-validated as the phone and the extensions are: a row that
        /// reached us another way must not become a key that dials somewhere else.
        /// </summary>
        private static List<PhoneButton> Validated(IEnumerable<PhoneButton> buttons)
        {
            var ordered = buttons.OrderBy(b => b.Position).ToList();

            foreach (var button in ordered)
            {
                var errors = button.Validate();
                if (errors.Count > 0)
                    throw new InvalidOperationException($"Phone key {button.Position} is invalid: {string.Join(" ", errors)}");
            }

            return ordered;
        }
    }
}
