using System.Globalization;
using System.Text;
using Techie.Pbx.Asterisk.Config;

namespace Techie.Pbx.Asterisk.Provisioning
{
    /// <summary>
    /// One phone's configuration, generated from its row and the extension it is linked to. Pure
    /// function: data in, text out, no lookups and no I/O — the file is never written to disk, it
    /// is generated for each request and handed straight to the phone (D88, mirroring D79).
    ///
    /// The format is plain <c>key = value</c> lines, one per line, not XML — Yealink's own shape,
    /// completely different from Polycom's attribute-per-element files. Every generated file must
    /// start with the literal <c>#!version:1.0.0.1</c> cookie or the phone refuses it outright.
    ///
    /// A phone with no extension still gets a valid file: the time and a provisioning poll, and no
    /// registration. That is what lets a phone auto-register itself, sit on a desk, and start
    /// working the moment an admin assigns it an extension and it polls again (D78, D88).
    /// </summary>
    public static class YealinkConfigRenderer
    {
        /// <summary>The line every Yealink phone requires as the first line of a config it accepts.</summary>
        private const string VersionCookie = "#!version:1.0.0.1";

        /// <summary>Yealink's own enum value for "expect an unencrypted UDP transport".</summary>
        private const int TransportUdp = 0;

        /// <summary>How long the phone's registration lasts before it renews, in seconds.</summary>
        private const int RegistrationExpiry = 3600;

        /// <summary>
        /// How often the phone re-polls its provisioning URL, in minutes. A few times a day:
        /// long enough not to be a load on the server, short enough that assigning an extension
        /// takes effect without anyone walking to the desk (mirrors D79's reasoning).
        /// </summary>
        private const int ProvisioningRepeatMinutes = 480;

        /// <summary>The last account slot: accounts 2 through this are disabled (D88).</summary>
        private const int LastUnusedAccount = 6;

        public static string Render(YealinkConfig config)
        {
            var phone = config.Phone;

            var phoneErrors = phone.Validate();
            if (phoneErrors.Count > 0)
                throw new InvalidOperationException($"Phone '{phone.Mac}' is invalid: {string.Join(" ", phoneErrors)}");

            if (config.Extension != null)
            {
                var extensionErrors = config.Extension.Validate();
                if (extensionErrors.Count > 0)
                {
                    throw new InvalidOperationException(
                        $"Extension '{config.Extension.Number}' is invalid: {string.Join(" ", extensionErrors)}");
                }
            }

            var sb = new StringBuilder();

            sb.Append(VersionCookie).Append('\n');
            sb.Append($"# Generated by TNPBX for {ConfText.Safe(phone.Mac, "mac")} per request. Nothing is stored on disk; edit the phone in TNPBX.\n");
            sb.Append('\n');

            Line(sb, "local_time.ntp_server1", ConfText.Safe(config.NtpServer, "ntp server"));
            Line(sb, "local_time.time_zone", ConfText.Safe(config.TimeZoneOffset, "time zone offset"));
            Line(sb, "local_time.time_format", "1");

            sb.Append('\n');
            Line(sb, "auto_provision.server.url", ConfText.Safe(config.ProvisioningUrl, "provisioning url"));

            if (config.ProvisioningUsername.Length > 0)
                Line(sb, "auto_provision.server.username", ConfText.Safe(config.ProvisioningUsername, "provisioning username"));

            if (config.ProvisioningPassword.Length > 0)
                Line(sb, "auto_provision.server.password", ConfText.Safe(config.ProvisioningPassword, "provisioning password"));

            Line(sb, "auto_provision.dhcp_option.enable", "1");
            Line(sb, "auto_provision.repeat.enable", "1");
            Line(sb, "auto_provision.repeat.minutes", Number(ProvisioningRepeatMinutes));

            sb.Append('\n');
            for (var account = 2; account <= LastUnusedAccount; account++)
                Line(sb, $"account.{account}.enable", "0");

            if (config.Extension == null)
            {
                sb.Append("\n# No extension is assigned to this phone yet, so it is given no registration.\n");
                return sb.ToString();
            }

            var extension = config.Extension;

            sb.Append('\n');
            Line(sb, "account.1.enable", "1");
            Line(sb, "account.1.label", ConfText.Safe(extension.Name, "extension name"));
            Line(sb, "account.1.display_name", ConfText.Safe(extension.Name, "extension name"));
            Line(sb, "account.1.auth_name", ConfText.Safe(extension.Number, "extension number"));
            Line(sb, "account.1.user_name", ConfText.Safe(extension.Number, "extension number"));
            Line(sb, "account.1.password", ConfText.Safe(extension.Secret, "extension secret"));
            Line(sb, "account.1.sip_server.1.address", ConfText.Safe(config.ServerAddress, "server address"));
            Line(sb, "account.1.sip_server.1.port", Number(config.SipPort));
            Line(sb, "account.1.sip_server.1.transport_type", Number(TransportUdp));
            Line(sb, "account.1.sip_server.1.expiry", Number(RegistrationExpiry));
            Line(sb, "account.1.subscribe_mwi", "1");
            Line(sb, "account.1.subscribe_mwi_to_vm", "1");
            Line(sb, "account.1.dtmf.type", "2");
            Line(sb, "account.1.nat.udp_update_enable", "1");
            Line(sb, "account.1.nat.udp_update_time", "60");
            Line(sb, "account.1.nat.rport", "1");

            sb.Append('\n');
            WriteCodecs(sb, config.Codecs);

            return sb.ToString();
        }

        /// <summary>One "key = value" line.</summary>
        private static void Line(StringBuilder sb, string key, string value) => sb.Append(key).Append(" = ").Append(value).Append('\n');

        private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

        /// <summary>The Yealink name and RTP payload type for the codecs this system offers (D73).</summary>
        private static (string Name, int PayloadType) YealinkCodec(string codec) => codec switch
        {
            "ulaw" => ("PCMU", 0),
            "alaw" => ("PCMA", 8),
            "g722" => ("G722", 9),
            "gsm" => ("GSM", 3),
            _ => throw new InvalidOperationException($"Refusing to write codec '{codec}': not one this system loads."),
        };

        /// <summary>
        /// One codec slot per codec present, in preference order, skipping anything this system
        /// has no Yealink name for.
        /// </summary>
        private static void WriteCodecs(StringBuilder sb, List<string> codecs)
        {
            var slot = 0;

            foreach (var codec in codecs)
            {
                if (codec is not ("ulaw" or "alaw" or "gsm" or "g722"))
                    continue;

                slot++;
                var (name, payloadType) = YealinkCodec(codec);

                Line(sb, $"account.1.codec.{slot}.enable", "1");
                Line(sb, $"account.1.codec.{slot}.name", name);
                Line(sb, $"account.1.codec.{slot}.payload_type", Number(payloadType));
                Line(sb, $"account.1.codec.{slot}.priority", Number(slot));
            }
        }
    }
}
