using System.Text;
using Techie.Pbx.Core.Models;

namespace Techie.Pbx.Asterisk.Provisioning
{
    /// <summary>
    /// The boot file every Yealink phone asks for first, under the one fixed name
    /// <see cref="YealinkFiles.BootFileName"/> — unlike Polycom's master file, it carries no MAC
    /// address at all (D89). It is a pointer and nothing else: it names the one config file the
    /// phone should include next, and that is where the MAC comes from, out of the request's own
    /// User-Agent header.
    ///
    /// It includes only the MAC-specific file. Real Yealink boot files can also point at a
    /// model-common config, but that would mean hosting and tracking a config archive per model
    /// we have no use for — the same reasoning D83 gives for not serving firmware (D90).
    /// </summary>
    public static class YealinkMasterRenderer
    {
        /// <summary>The line every Yealink phone requires as the first line of a config it accepts.</summary>
        private const string VersionCookie = "#!version:1.0.0.1";

        public static string Render(string mac)
        {
            if (!Phone.IsValidMac(mac))
                throw new InvalidOperationException($"Refusing to generate a boot file for '{mac}', which is not a MAC address.");

            var sb = new StringBuilder();

            sb.Append(VersionCookie).Append('\n');
            sb.Append("# Generated by TNPBX per request. Nothing is stored on disk; edit the phone in TNPBX.\n");
            sb.Append('\n');
            sb.Append($"include:config \"{YealinkFiles.ConfigFileName(mac)}\"\n");

            return sb.ToString();
        }
    }
}
