using System.Text;
using Techie.Pbx.Contracts;

namespace Techie.Pbx.Helper.Firewall
{
    /// <summary>
    /// The whole nftables ruleset, as text. A pure function like the Asterisk renderers — rules
    /// in, file out — so what a message turns into can be read in a golden file rather than
    /// guessed at from a root process's behaviour.
    ///
    /// The policy it renders is fixed (D143) and none of it comes from the message:
    ///
    /// <list type="bullet">
    /// <item>One table, <c>inet tnpbx-input</c>, so a single ruleset covers IPv4 and IPv6.</item>
    /// <item>One base chain, <c>input</c>, hook input, priority 0, <b>policy drop</b>.</item>
    /// <item>The four safety rules first, always, written here and nowhere else: loopback,
    /// established/related, ICMP (both families) and SSH. A firewall.apply can only ever widen
    /// what follows them, so no message content can lock the machine out.</item>
    /// <item>Then one accept per rule the message carried, with its label as the nft comment.</item>
    /// </list>
    ///
    /// The table is added, deleted and built again. <c>nft -f</c> applies a file as one
    /// transaction, so that sequence replaces exactly this table with no moment in between where
    /// the ruleset is half loaded — and it touches no other table, which is what keeps fail2ban's
    /// <c>f2b-table</c> (a separate table at priority -1, so it runs first) out of our business.
    /// </summary>
    public static class NftRuleset
    {
        public const string ChainName = "input";

        /// <summary>The port the safety rules keep open whatever a message says.</summary>
        public const int SshPort = 22;

        public const string TableName = "tnpbx-input";

        public static string Render(IReadOnlyList<FirewallRule> rules)
        {
            // Re-validated here as well as at both ends of the socket: this is the last thing
            // between a rule and a file a root process feeds to nft (the same reason the conf
            // renderers re-validate every row).
            foreach (var rule in rules)
            {
                var errors = rule.Validate();
                if (errors.Count > 0)
                    throw new InvalidOperationException($"Invalid firewall rule: {string.Join(" ", errors)}");
            }

            var sb = new StringBuilder();

            sb.Append("# Generated by TNPBX. Do not edit: the helper rewrites this file on every firewall apply.\n");
            sb.Append("#\n");
            sb.Append("# The table is added, deleted and then built again, all in one nft transaction, so loading\n");
            sb.Append("# this file replaces exactly this table and leaves every other one alone — fail2ban's\n");
            sb.Append("# f2b-table included, which is its own table at priority -1 and so runs first (D143).\n");
            sb.Append('\n');

            sb.Append($"table inet {TableName}\n");
            sb.Append($"delete table inet {TableName}\n");
            sb.Append('\n');

            sb.Append($"table inet {TableName} {{\n");
            sb.Append($"\tchain {ChainName} {{\n");
            sb.Append("\t\ttype filter hook input priority 0; policy drop;\n");
            sb.Append('\n');

            sb.Append("\t\t# Safety rules. The helper writes these itself and no message can reach them, so no\n");
            sb.Append("\t\t# firewall apply can lock this machine out — by construction, not by review (D142).\n");
            sb.Append("\t\tiif \"lo\" accept\n");
            sb.Append("\t\tct state established,related accept\n");
            sb.Append("\t\tmeta l4proto { icmp, ipv6-icmp } accept\n");
            sb.Append($"\t\ttcp dport {SshPort} accept\n");
            sb.Append('\n');

            if (rules.Count == 0)
            {
                sb.Append("\t\t# The application asked for no open ports, so there are none: the safety rules\n");
                sb.Append("\t\t# above are the whole of what this machine accepts.\n");
            }
            else
            {
                sb.Append("\t\t# What the application asked for.\n");

                foreach (var rule in rules)
                    sb.Append($"\t\t{Protocol(rule)} dport {rule.PortRange} accept comment \"{rule.Label}\"\n");
            }

            sb.Append("\t}\n");
            sb.Append("}\n");

            return sb.ToString();
        }

        /// <summary>
        /// The protocol as nft spells it. A switch rather than a lowercased enum name, so adding a
        /// member to <see cref="FirewallProtocol"/> without deciding what it renders as is a
        /// failure here and not a silently wrong ruleset.
        /// </summary>
        private static string Protocol(FirewallRule rule) => rule.Protocol switch
        {
            FirewallProtocol.Tcp => "tcp",
            FirewallProtocol.Udp => "udp",
            _ => throw new InvalidOperationException($"Unknown firewall protocol '{rule.Protocol}'."),
        };
    }
}
