using log4net;
using Microsoft.AspNetCore.Mvc;
using Techie.Pbx.Core;
using Techie.Pbx.Core.Data;
using Techie.Pbx.Core.Security;

namespace Techie.Pbx.Web.Controllers
{
    /// <summary>
    /// The extension actions that answer with data rather than with a piece of the page: showing
    /// and regenerating the SIP password. Everything else about extensions is a Razor Pages
    /// handler returning HTML for htmx.
    /// </summary>
    [ApiController]
    [Route("api/extensions")]
    public class ExtensionsController : ControllerBase
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(ExtensionsController));

        private readonly ExtensionRepository extensions;

        public ExtensionsController()
        {
            this.extensions = new ExtensionRepository(PbxDatabase.Current);
        }

        /// <summary>
        /// The SIP password for one extension, on explicit request. Who asked is logged; the
        /// value never is.
        /// </summary>
        [HttpGet("{extensionID:long}/secret")]
        public IActionResult GetSecret(long extensionID)
        {
            var extension = this.extensions.GetByID(extensionID);
            if (extension == null)
                return this.NotFound(new MessageResponse("That extension no longer exists."));

            Log.Info($"SIP password for extension {extension.Number} shown to {this.User.Identity?.Name}");
            return this.Ok(new SecretResponse { Number = extension.Number, Secret = extension.Secret });
        }

        /// <summary>
        /// Replaces the SIP password with a new random one and returns it. The phone keeps
        /// working until the next apply, and then has to be reconfigured.
        /// </summary>
        [HttpPost("{extensionID:long}/secret")]
        public IActionResult RegenerateSecret(long extensionID)
        {
            var extension = this.extensions.GetByID(extensionID);
            if (extension == null)
                return this.NotFound(new MessageResponse("That extension no longer exists."));

            extension.Secret = SecretGenerator.Create();

            try
            {
                this.extensions.Update(extension);
            }
            catch (ValidationFailedException ex)
            {
                Log.Error($"Could not regenerate the SIP password for extension {extension.Number}: {ex.Message}");
                return this.BadRequest(new MessageResponse(ex.Message));
            }

            Log.Info($"SIP password for extension {extension.Number} regenerated by {this.User.Identity?.Name}");
            return this.Ok(new SecretResponse { Number = extension.Number, Secret = extension.Secret });
        }
    }
}
